### ISSUE TITLE
Selling registration

### ISSUE THREAD

**Issue by teriesu** [yepedraza/SoftwareDevelopment-G7#16]
Crear la interfaz para el registro de las ventas (Identificador de la venta, valor total de la venta, identificador, cantidad, y precio unitario de cada producto, fecha de venta, documento de identificación y nombre del cliente, y además deberá contar con un encargado de gestionar dicha venta, es decir, vendedor), teniendo en cuenta las historias de usuario:

**Historia de usuario: HU_006**
**Como** vendedor o administrador
**Dado** que ingreso al sistema de ventas
**Cuando** necesite registrar una venta
**Entonces** podré ingresar los datos relacionados a una venta

**Historia de usuario: HU_007**
**Como** vendedor o administrador
**Dado** que ingreso al sistema de ventas
**Cuando** registre una venta
**Entonces** podré ver que se almacenó correctamente

**Comment by yepedraza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Registro de ventas](https://trello.com/c/TAwtHTYy/25-registro-de-ventas)
